const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const main = read('src/main.cjs');
const gateway = read('src/model-gateway.cjs');
const docs = read('src/documents.cjs');
const preload = read('src/preload.cjs');
const renderer = read('src/renderer/app.js');
const html = read('src/renderer/index.html');
const builder = read('electron-builder.yml');
const pkg = JSON.parse(read('package.json'));
const failures = [];
const must = (condition, message) => { if (!condition) failures.push(message); };

must(pkg.name === 'chp-desktop', 'package must be chp-desktop');
must(fs.existsSync(path.join(root, 'portable.flag')), 'portable.flag missing');
must(main.includes("app.setPath('userData'"), 'portable userData relocation missing');
must(main.includes("path.join(dataRoot, 'chp-api.json')"), 'portable API config path missing');
must(main.includes("ipcMain.handle('workspace:choose'"), 'workspace picker missing');
must(main.includes("ipcMain.handle('files:search'"), 'file search missing');
must(main.includes("ipcMain.handle('terminal:run'"), 'terminal missing');
must(main.includes("ipcMain.handle('artifacts:list'"), 'artifacts missing');
must(main.includes("const TOOL_DEFS = ["), 'work-agent tools missing');
must(main.includes("mode === 'work'"), 'work-agent loop missing');
must(main.includes('safeJoin'), 'workspace path guard missing');
must(gateway.includes("protocol: 'anthropic'"), 'Anthropic gateway missing');
must(gateway.includes("cfg.protocol === 'openai'"), 'OpenAI gateway missing');
must(gateway.includes('tool_calls'), 'OpenAI tool calling missing');
must(gateway.includes("type: 'tool_use'"), 'Anthropic tool calling missing');
must(gateway.includes('text/event-stream'), 'streaming support missing');
must(preload.includes("ipcRenderer.invoke('config:test'"), 'connection test bridge missing');
must(preload.includes("listen('chat:tool'"), 'tool-event bridge missing');
must(preload.includes("ipcRenderer.invoke('artifacts:list'"), 'artifact bridge missing');
must(renderer.includes("sendPrompt($('#workPrompt').value,'work')"), 'Work Agent UI not wired');
must(renderer.includes('testSettings'), 'model test UI not wired');
must(renderer.includes('importSettings'), 'config import UI not wired');
must(html.includes('Anthropic'), 'Anthropic settings UI missing');
must(html.includes('OpenAI Compatible'), 'OpenAI settings UI missing');
must(html.includes('MODEL API'), 'online model status missing');
must(!html.includes('OFFLINE'), 'stale OFFLINE UI remains');
must(!html.includes('外网已阻断'), 'stale network-block UI remains');
must(docs.includes("ext === '.pdf'"), 'PDF parser missing');
must(docs.includes("ext === '.docx'"), 'DOCX parser missing');
must(docs.includes("'.xlsx'"), 'XLSX parser missing');
must(docs.includes("ext === '.pptx'"), 'PPTX parser missing');
must(builder.includes('executableName: chp'), 'chp executable name missing');
must(builder.includes('target: dir'), 'portable directory target missing');

if (failures.length) {
  console.error('CHP_SELFTEST_FAIL');
  for (const f of failures) console.error('-', f);
  process.exit(1);
}
console.log('CHP_SELFTEST_PASS');
console.log('portable_storage=PASS');
console.log('lobehub_cloud_dependency=REMOVED_FROM_CHP_RUNTIME');
console.log('anthropic_openai_gateway=PASS');
console.log('streaming_tool_calls=PASS');
console.log('chat_attachments=PASS');
console.log('work_agent_tools=PASS');
console.log('workspace_path_isolation=PASS');
console.log('files_terminal_tasks_artifacts=PASS');
console.log('pdf_docx_xlsx_pptx=PASS');
console.log('renderer_online_model_ui=PASS');
