const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={chats:[],activeChatId:null,workspace:{root:'',id:''},projects:[],tasks:[],config:null,editorPath:'',pendingDocuments:[],runs:new Map(),tools:[],ptyId:null,artifacts:[],skills:[],mcp:[],computer:{enabled:false}};
const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;const basename=(p='')=>p.replace(/[\\/]+$/,'').split(/[\\/]/).pop()||'';const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='files')refreshFiles();if(name==='tasks')renderTasks();if(name==='tools')refreshTools()}
function currentChat(){return state.chats.find(x=>x.id===state.activeChatId)}
function ensureChat(title='新对话'){let c=currentChat();if(!c){c={id:uid(),title,createdAt:Date.now(),updatedAt:Date.now(),messages:[]};state.chats.unshift(c);state.activeChatId=c.id}return c}
async function saveChats(){await window.chp.chat.saveAll(state.chats);renderChatList()}
function renderChatList(){const q=$('#sidebarSearch').value.trim().toLowerCase();$('#chatList').innerHTML=state.chats.filter(c=>!q||c.title.toLowerCase().includes(q)).slice(0,50).map(c=>`<div class="chat-item ${c.id===state.activeChatId?'active':''}" data-chat-id="${c.id}"><span class="dot"></span><span>${esc(c.title)}</span></div>`).join('');$$('#chatList .chat-item').forEach(el=>el.onclick=()=>{state.activeChatId=el.dataset.chatId;renderChat();renderChatList()})}
function renderChat(){const chat=currentChat();$('#chatTitle').textContent=chat?.title||'新对话';const list=chat?.messages||[];$('#emptyState').style.display=list.length?'none':'block';$('#messages').querySelectorAll('.message').forEach(x=>x.remove());for(const m of list){const div=document.createElement('div');div.className=`message ${m.role}${m.error?' error':''}`;div.dataset.messageId=m.id||'';div.textContent=m.content||'';if(m.meta)div.title=m.meta;$('#messages').appendChild(div)}$('#messages').scrollTop=$('#messages').scrollHeight;renderRunButtons()}
function renderRunButtons(){const active=[...state.runs.values()].filter(r=>r.chatId===state.activeChatId);$('#send').textContent=active.length?'■':'➤';$('#workStatus').textContent=state.runs.size?`RUN ${state.runs.size}`:'IDLE'}
function buildDocumentContext(docs){return docs.map(d=>`\n\n--- LOCAL ATTACHMENT: ${d.name} (${d.kind}) ---\n${d.content}\n--- END ATTACHMENT ---`).join('')}
async function pickDocuments(){try{const docs=await window.chp.files.pick();if(!docs?.length)return;state.pendingDocuments=docs;$('#insertFile').textContent=`＋ 文件 (${docs.length})`;$('#contextStrip').innerHTML=docs.map(d=>`<span>${esc(d.name)}</span>`).join('');$('#prompt').focus()}catch(e){toast(e.message,'error')}}
function autoSizePrompt(){const el=$('#prompt');el.style.height='auto';el.style.height=`${Math.min(180,Math.max(48,el.scrollHeight))}px`}
function activeRunForChat(chatId){return[...state.runs.values()].find(r=>r.chatId===chatId)}
async function startRun({text,mode='chat',workspaceRoot=''}){const prompt=String(text||'').trim();if(!prompt)return;const chat=ensureChat(mode==='work'?`Work · ${basename(workspaceRoot||state.workspace.root)||'项目'}`:'新对话');if(chat.messages.length===0)chat.title=mode==='work'?`Work · ${prompt.slice(0,24)}`:prompt.slice(0,30)+(prompt.length>30?'…':'');const docs=mode==='chat'?state.pendingDocuments:[];const label=docs.length?`\n\n[已附加 ${docs.map(d=>d.name).join('、')}]`:'';const user={id:uid(),role:'user',content:prompt+label,modelContent:prompt+buildDocumentContext(docs)};const assistant={id:uid(),role:'assistant',content:'',meta:mode==='work'?`Work · ${workspaceRoot}`:''};chat.messages.push(user,assistant);chat.updatedAt=Date.now();state.pendingDocuments=[];$('#insertFile').textContent='＋ 文件';$('#contextStrip').innerHTML='';const requestId=uid();state.runs.set(requestId,{requestId,chatId:chat.id,messageId:assistant.id,mode,workspaceRoot,startedAt:Date.now()});if(mode==='chat'){$('#prompt').value='';autoSizePrompt()}else $('#workPrompt').value='';await saveChats();renderChat();window.chp.chat.start({requestId,mode,workspaceRoot,messages:chat.messages.filter(m=>m.id!==assistant.id).map(m=>({role:m.role,content:m.modelContent||m.content}))});renderRunButtons()}
async function cancelActive(){const run=activeRunForChat(state.activeChatId);if(run)await window.chp.chat.cancel(run.requestId)}
function findRunMessage(requestId){const run=state.runs.get(requestId);if(!run)return{};const chat=state.chats.find(c=>c.id===run.chatId);const msg=chat?.messages.find(m=>m.id===run.messageId);return{run,chat,msg}}
async function finishRun(requestId,error=''){const{run,chat,msg}=findRunMessage(requestId);if(!run)return;if(error&&msg){msg.content=msg.content||`执行失败：${error}`;msg.error=true}state.runs.delete(requestId);if(chat){chat.updatedAt=Date.now();await window.chp.chat.saveAll(state.chats)}renderChatList();if(state.activeChatId===run.chatId)renderChat();renderRunButtons();await refreshArtifacts()}
function toolEvent(evt){state.tools.unshift({...evt,at:Date.now()});state.tools=state.tools.slice(0,100);renderToolTimeline()}
function renderToolTimeline(){const box=$('#toolTimeline');if(!state.tools.length){box.innerHTML='<div class="tool-empty">Agent 工具调用会显示在这里。</div>';return}box.innerHTML=state.tools.slice(0,40).map(e=>`<div class="tool-event ${e.phase}"><div><strong>${esc(e.tool?.name||'tool')}</strong><span>${esc(e.phase)}</span></div><small>${new Date(e.at).toLocaleTimeString()} · ${esc(e.error||JSON.stringify(e.tool?.input||{}).slice(0,180))}</small></div>`).join('')}
async function chooseWorkspace(){const p=await window.chp.workspace.choose();if(p){state.workspace={id:p.id,root:p.root};await loadProjects();updateWorkspaceUI();await Promise.all([refreshFiles(),refreshIndex()])}}
async function loadProjects(){state.projects=await window.chp.workspace.list();$('#recentProjects').innerHTML='<option value="">最近项目</option>'+state.projects.map(p=>`<option value="${esc(p.id)}" ${p.id===state.workspace.id?'selected':''}>${esc(p.name)} — ${esc(p.root)}</option>`).join('')}
async function switchProject(id){if(!id)return;const p=await window.chp.workspace.switch(id);state.workspace={id:p.id,root:p.root};updateWorkspaceUI();await Promise.all([refreshFiles(),refreshIndex()])}
function updateWorkspaceUI(){const root=state.workspace.root||'';$('#workspaceName').textContent=root?basename(root):'选择项目文件夹';$('#workspacePath').textContent=root||'未选择';$('#inspectorWorkspace').textContent=root?basename(root):'—';$('#projectSummary').textContent=root?`当前项目：${root}。Work Agent 的每次运行会绑定启动时的项目根目录，切换项目不会污染正在执行的任务。`:'选择一个本地项目文件夹开始工作。'}
async function refreshFiles(){if(!state.workspace.root){$('#fileList').innerHTML='';return}try{const files=await window.chp.files.list('');$('#fileCount').textContent=files.length;$('#fileList').innerHTML=files.map(f=>`<div class="file-row ${f.type}" data-file="${encodeURIComponent(f.path)}" data-type="${f.type}">${f.type==='dir'?'▰':'·'} ${esc(f.name)}</div>`).join('');$$('#fileList .file-row').forEach(el=>el.onclick=async()=>{if(el.dataset.type!=='file')return;await openFile(decodeURIComponent(el.dataset.file))})}catch(e){$('#fileList').innerHTML=`<div class="search-row">${esc(e.message)}</div>`}}
async function openFile(rel){try{const result=await window.chp.files.read(rel);state.editorPath=result.path;$('#editorPath').textContent=`${result.path} · ${result.kind||'text'}`;$('#editor').value=result.content}catch(e){$('#editorPath').textContent=e.message}}
async function searchFiles(){const q=$('#fileSearch').value.trim();if(!q)return;$('#searchResults').innerHTML='<div class="search-row">搜索中…</div>';try{const results=await window.chp.index.search(q);$('#searchResults').innerHTML=results.map(r=>`<div class="search-row" data-file="${encodeURIComponent(r.path)}"><strong>${esc(r.path)}${r.line?`:${r.line}`:''}</strong>${r.preview?`<small>${esc(r.preview)}</small>`:''}</div>`).join('')||'<div class="search-row">没有结果</div>';$$('#searchResults .search-row[data-file]').forEach(el=>el.onclick=()=>openFile(decodeURIComponent(el.dataset.file)))}catch(e){$('#searchResults').innerHTML=`<div class="search-row">${esc(e.message)}</div>`}}
async function buildIndex(){if(!state.workspace.root)return chooseWorkspace();$('#indexStatus').textContent='索引中…';try{const r=await window.chp.index.build();$('#indexStatus').textContent=`${r.count} 文件 · ${(r.bytes/1048576).toFixed(1)} MB`}catch(e){$('#indexStatus').textContent=e.message}}
async function refreshIndex(){if(!state.workspace.root){$('#indexStatus').textContent='未索引';return}const r=await window.chp.index.get();$('#indexStatus').textContent=r?`${r.count} 文件 · ${(r.bytes/1048576).toFixed(1)} MB`:'未索引'}
async function runCommand(){const command=$('#commandInput').value.trim();if(!command)return;$('#ptyOutput').textContent+=`\n\n$ ${command}\n`;const result=await window.chp.terminal.run(command);$('#ptyOutput').textContent+=`${result.stdout}${result.stderr?`\n[stderr]\n${result.stderr}`:''}\n[exit ${result.code}]`;$('#ptyOutput').scrollTop=$('#ptyOutput').scrollHeight}
async function startPty(){if(state.ptyId)return;try{const s=await window.chp.pty.start({cols:120,rows:30});state.ptyId=s.id;$('#ptyState').textContent=`PTY · ${s.command}`;$('#ptyOutput').textContent=''}catch(e){toast(e.message,'error')}}
async function stopPty(){if(!state.ptyId)return;await window.chp.pty.kill(state.ptyId);state.ptyId=null;$('#ptyState').textContent='未启动'}
async function sendPty(){const value=$('#ptyInput').value;if(!value)return;if(!state.ptyId)await startPty();if(state.ptyId){await window.chp.pty.write(state.ptyId,value+'\r');$('#ptyInput').value=''}}
function renderTasks(){const n=state.tasks.length;$('#taskCount').textContent=n;$('#taskBoard').innerHTML=state.tasks.map(t=>`<div class="task-card ${t.done?'done':''}" data-task="${t.id}"><h3>${esc(t.title)}</h3><p>${esc(t.note||'本地任务')}</p><div class="task-actions"><button data-toggle>${t.done?'恢复':'完成'}</button><button data-delete>删除</button></div></div>`).join('')||'<div class="task-card"><h3>还没有任务</h3><p>任务保存在 chp/data/tasks.json。</p></div>';$$('#taskBoard .task-card[data-task]').forEach(card=>{card.querySelector('[data-toggle]').onclick=async()=>{const t=state.tasks.find(x=>x.id===card.dataset.task);t.done=!t.done;await window.chp.tasks.set(state.tasks);renderTasks()};card.querySelector('[data-delete]').onclick=async()=>{state.tasks=state.tasks.filter(x=>x.id!==card.dataset.task);await window.chp.tasks.set(state.tasks);renderTasks()}})}
async function addTask(){const title=prompt('任务名称');if(!title?.trim())return;state.tasks.unshift({id:uid(),title:title.trim(),note:'',done:false,createdAt:Date.now()});await window.chp.tasks.set(state.tasks);renderTasks()}
async function refreshArtifacts(){state.artifacts=await window.chp.artifacts.list();$('#artifactCount').textContent=state.artifacts.length;$('#artifactList').innerHTML=state.artifacts.slice(0,12).map(a=>`<button class="artifact-row" data-artifact="${esc(a.name)}"><strong>${esc(a.name)}</strong><small>${(a.size/1024).toFixed(1)} KB</small></button>`).join('')||'<div class="tool-empty">暂无产物</div>';$$('[data-artifact]').forEach(b=>b.onclick=()=>window.chp.artifacts.reveal(b.dataset.artifact))}
async function refreshSkills(){state.skills=await window.chp.skills.list();$('#skillList').innerHTML=state.skills.map(s=>`<div class="feature-row"><div><strong>${esc(s.name)}</strong><small>${esc(s.description||s.id)}</small></div><span>${s.builtin?'BUILT-IN':'LOCAL'}</span></div>`).join('')}
async function refreshMcp(){state.mcp=await window.chp.mcp.servers();$('#mcpList').innerHTML=state.mcp.map(s=>`<button class="feature-row feature-button" data-mcp="${esc(s.id)}"><div><strong>${esc(s.name)}</strong><small>${esc(s.command||'')}</small></div><span>${s.enabled?'ON':'OFF'}</span></button>`).join('')||'<div class="tool-empty">暂无 MCP Server</div>';$$('[data-mcp]').forEach(b=>b.onclick=()=>showMcpTools(b.dataset.mcp))}
async function showMcpTools(id){$('#mcpTools').textContent='连接中…';try{const tools=await window.chp.mcp.tools(id);$('#mcpTools').innerHTML=tools.map(t=>`<div class="mcp-tool"><strong>${esc(t.name)}</strong><small>${esc(t.description||'')}</small></div>`).join('')||'该 Server 没有工具。'}catch(e){$('#mcpTools').textContent=e.message}}
async function addMcp(){const name=prompt('MCP Server 名称','Local MCP');if(!name)return;const command=prompt('启动命令（完整路径）');if(!command)return;const argText=prompt('参数，用空格分隔','');state.mcp.push({id:uid(),name,command,args:(argText||'').split(/\s+/).filter(Boolean),env:{},enabled:true});state.mcp=await window.chp.mcp.save(state.mcp);await refreshMcp()}
async function refreshComputer(){const s=await window.chp.computer.status();state.computer=s;$('#computerEnabled').checked=!!s.enabled}
async function captureScreen(){try{const r=await window.chp.computer.capture();$('#screenPreview').src=r.dataUrl;toast(`已捕获 ${r.width}×${r.height}`)}catch(e){toast(e.message,'error')}}
async function createArtifact(){const name=$('#artifactName').value.trim()||'artifact',format=$('#artifactFormat').value,content=$('#artifactContent').value;$('#artifactMessage').textContent='生成中…';try{const a=await window.chp.artifacts.create({name,format,title:name,content});$('#artifactMessage').textContent=`已生成 ${a.name}`;await refreshArtifacts()}catch(e){$('#artifactMessage').textContent=e.message}}
async function refreshTools(){await Promise.all([refreshSkills(),refreshMcp(),refreshComputer(),refreshArtifacts()])}
async function loadSettings(){state.config=await window.chp.config.get();$('#settingProtocol').value=state.config.protocol||'anthropic';$('#settingAuth').value=state.config.auth_scheme||'bearer';$('#settingEndpoint').value=state.config.base_url||'';$('#settingApiKey').value=state.config.api_key||'';$('#settingModel').value=state.config.model||'';$('#settingTemperature').value=state.config.temperature??0.7;$('#settingMaxTokens').value=state.config.max_tokens??8192;$('#settingSystem').value=state.config.system_prompt||'';$('#modelName').textContent=state.config.model||'未配置模型';$('#endpointName').textContent=state.config.base_url||'模型接入待配置';$('#inspectorModel').textContent=state.config.model||'—';$('#inspectorProtocol').textContent=state.config.protocol||'—'}
function settingsPayload(){return{protocol:$('#settingProtocol').value,auth_scheme:$('#settingAuth').value,base_url:$('#settingEndpoint').value.trim(),api_key:$('#settingApiKey').value,model:$('#settingModel').value.trim(),temperature:Number($('#settingTemperature').value||0.7),max_tokens:Number($('#settingMaxTokens').value||8192),system_prompt:$('#settingSystem').value}}
async function saveSettings(){try{state.config=await window.chp.config.set(settingsPayload());$('#settingsMessage').textContent='已保存。';await loadSettings()}catch(e){$('#settingsMessage').textContent=e.message}}
async function testSettings(){const el=$('#settingsMessage');el.textContent='连接测试中…';try{const r=await window.chp.config.test(settingsPayload());el.textContent=`连接成功 · ${r.protocol} · ${r.model} · ${r.output}`}catch(e){el.textContent=`连接失败：${e.message}`}}
async function importSettings(){try{const r=await window.chp.config.importFile();if(r){state.config=r;await loadSettings();$('#settingsMessage').textContent='已导入 chp-api.json'}}catch(e){$('#settingsMessage').textContent=e.message}}
function quickAction(action){const map={scan:'完整扫描当前项目：先建立/读取索引，识别关键模块、运行入口、依赖、风险和优先问题。不要只给建议；能验证的请运行验证。',review:'对当前项目做真实代码审查，优先找 bug、并发/状态污染、错误处理、安全、性能和发布风险。给出文件位置并修复明确问题。',plan:'基于当前项目现状生成实施计划；先检查代码和现有任务，再按依赖顺序输出并把计划保存为 Artifact。',docs:'读取当前项目实际结构与入口，生成准确的 README/使用文档，并保存为 DOCX 或 Markdown Artifact。'};$('#workPrompt').value=map[action]||'';$('#workPrompt').focus()}
function toast(text,type='ok'){const old=document.querySelector('.toast');old?.remove();const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
async function init(){state.workspace=await window.chp.workspace.get();state.chats=await window.chp.chat.getAll();state.tasks=await window.chp.tasks.get();if(state.chats[0])state.activeChatId=state.chats[0].id;updateWorkspaceUI();await loadProjects();renderChatList();renderChat();renderTasks();await Promise.all([loadSettings(),refreshFiles(),refreshIndex(),refreshArtifacts(),refreshSkills(),refreshMcp(),refreshComputer()]);
  $$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#openSettings').onclick=()=>switchView('settings');$('#newChat').onclick=async()=>{state.activeChatId=null;ensureChat();await saveChats();renderChat()};$('#chooseWorkspace').onclick=chooseWorkspace;$('#recentProjects').onchange=e=>switchProject(e.target.value);$('#refreshProject').onclick=()=>Promise.all([refreshFiles(),refreshIndex(),refreshArtifacts()]);$('#buildIndex').onclick=buildIndex;$('#sidebarSearch').oninput=renderChatList;
  $('#prompt').oninput=autoSizePrompt;$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();startRun({text:$('#prompt').value,mode:'chat'})}};$('#send').onclick=()=>activeRunForChat(state.activeChatId)?cancelActive():startRun({text:$('#prompt').value,mode:'chat'});$('#clearChat').onclick=async()=>{const c=currentChat();if(c){c.messages=[];await saveChats();renderChat()}};$$('.suggestions button').forEach(b=>b.onclick=()=>startRun({text:b.dataset.prompt,mode:'chat'}));$('#insertFile').onclick=pickDocuments;$('#attachWorkspace').onclick=()=>{if(!state.workspace.root)return chooseWorkspace();$('#prompt').value+=`\n\n请结合当前项目 ${state.workspace.root} 分析。`;autoSizePrompt()};
  $$('.quick-grid button').forEach(b=>b.onclick=()=>quickAction(b.dataset.action));$('#runWork').onclick=()=>{if(!state.workspace.root)return chooseWorkspace();startRun({text:$('#workPrompt').value,mode:'work',workspaceRoot:state.workspace.root})};
  $('#fileSearchBtn').onclick=searchFiles;$('#fileSearch').onkeydown=e=>{if(e.key==='Enter')searchFiles()};$('#saveFile').onclick=async()=>{if(!state.editorPath)return;await window.chp.files.write({rel:state.editorPath,content:$('#editor').value});$('#editorPath').textContent=`${state.editorPath} · 已保存`};
  $('#runCommand').onclick=runCommand;$('#commandInput').onkeydown=e=>{if(e.key==='Enter')runCommand()};$('#startPty').onclick=startPty;$('#stopPty').onclick=stopPty;$('#sendPty').onclick=sendPty;$('#ptyInput').onkeydown=e=>{if(e.key==='Enter')sendPty()};
  $('#addTask').onclick=addTask;$('#saveSettings').onclick=saveSettings;$('#testSettings').onclick=testSettings;$('#importSettings').onclick=importSettings;$('#addMcp').onclick=addMcp;$('#computerEnabled').onchange=async e=>{await window.chp.computer.enable(e.target.checked);await refreshComputer()};$('#captureScreen').onclick=captureScreen;$('#clickScreen').onclick=()=>window.chp.computer.click({x:Number($('#clickX').value),y:Number($('#clickY').value),button:'left'}).catch(e=>toast(e.message,'error'));$('#typeScreen').onclick=()=>window.chp.computer.type($('#typeText').value).catch(e=>toast(e.message,'error'));$('#keyScreen').onclick=()=>window.chp.computer.key($('#keyText').value).catch(e=>toast(e.message,'error'));$('#createArtifact').onclick=createArtifact;
  window.chp.chat.onDelta(({requestId,delta})=>{const{run,msg}=findRunMessage(requestId);if(!run||!msg)return;msg.content+=delta;if(state.activeChatId===run.chatId)renderChat()});window.chp.chat.onDone(({requestId})=>finishRun(requestId));window.chp.chat.onError(({requestId,message})=>finishRun(requestId,message));window.chp.chat.onTool(toolEvent);window.chp.chat.onUsage(()=>{});window.chp.pty.onData(({id,data})=>{if(id!==state.ptyId)return;$('#ptyOutput').textContent+=data;$('#ptyOutput').scrollTop=$('#ptyOutput').scrollHeight});window.chp.pty.onExit(({id,exitCode})=>{if(id===state.ptyId){state.ptyId=null;$('#ptyState').textContent=`已退出 · ${exitCode}`}})
}
init().catch(e=>{console.error(e);document.body.innerHTML=`<pre style="color:#fff;padding:30px;white-space:pre-wrap">${esc(e.stack||e.message)}</pre>`});
